apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: storefront.zone-kubernetes-dns
  namespace: storefront
spec:
  tier: storefront
  order: 10
  selector: all()
  serviceAccountSelector: ''
  egress:
    - action: Allow
      protocol: UDP
      source: {}
      destination:
        nets:
          - 0.0.0.0/0
        ports:
          - '53'
    - action: Allow
      protocol: TCP
      source: {}
      destination:
        nets:
          - 0.0.0.0/0
        ports:
          - '53'
  types:
    - Egress
